#!/usr/bin/env bash
# =============================================================================
# MAINFRAME/scripts/file/bulk-rename.sh - Bulk File Renamer
# =============================================================================
# Description: Renames files in bulk using patterns, regex, or sequential
#              numbering. Supports dry-run, undo generation, and recursion.
# Version: 1.0.0
# Requires: Bash 4.0+
# =============================================================================

set -o pipefail

source "${MAINFRAME_ROOT:-$HOME/.mainframe}/lib/common.sh"

# Configuration
DRY_RUN=false
RECURSIVE=false
TARGET_DIR="."
PATTERN=""
REPLACEMENT=""
MODE="regex"  # regex, prefix, suffix, sequential, lowercase, uppercase
START_NUM=1
UNDO_FILE=""

usage() {
    cat <<EOF
Usage: bulk-rename.sh [options] <pattern> <replacement>

Bulk rename files using various strategies.

Modes:
    regex       Regex find/replace on filenames (default)
    prefix      Add prefix to all files
    suffix      Add suffix before extension
    sequential  Rename to sequential numbers
    lowercase   Convert filenames to lowercase
    uppercase   Convert filenames to uppercase

Options:
    -m, --mode <mode>    Rename mode (default: regex)
    -d, --dir <path>     Target directory (default: .)
    -r, --recursive      Process subdirectories
    -n, --dry-run        Preview changes without renaming
    -s, --start <num>    Starting number for sequential mode
    --undo <file>        Generate undo script
    -h, --help           Show this help
EOF
    exit 0
}

parse_args() {
    local positional=()
    while [[ $# -gt 0 ]]; do
        case "$1" in
            -m|--mode)      MODE="$2"; shift 2 ;;
            -d|--dir)       TARGET_DIR="$2"; shift 2 ;;
            -r|--recursive) RECURSIVE=true; shift ;;
            -n|--dry-run)   DRY_RUN=true; shift ;;
            -s|--start)     START_NUM="$2"; shift 2 ;;
            --undo)         UNDO_FILE="$2"; shift 2 ;;
            -h|--help)      usage ;;
            -*)             log_error "Unknown option: $1"; usage ;;
            *)              positional+=("$1"); shift ;;
        esac
    done

    PATTERN="${positional[0]:-}"
    REPLACEMENT="${positional[1]:-}"
}

find_files() {
    local dir="$1"
    if [[ "$RECURSIVE" == true ]]; then
        find "$dir" -type f ! -path '*/\.*' 2>/dev/null | sort
    else
        find "$dir" -maxdepth 1 -type f ! -name '.*' 2>/dev/null | sort
    fi
}

rename_file() {
    local old_path="$1"
    local new_path="$2"

    if [[ "$old_path" == "$new_path" ]]; then
        return
    fi

    if [[ -e "$new_path" ]]; then
        log_warn "Skipping (target exists): $new_path"
        return
    fi

    if [[ "$DRY_RUN" == true ]]; then
        echo "  $(basename "$old_path") -> $(basename "$new_path")"
    else
        local new_dir
        new_dir=$(dirname "$new_path")
        [[ -d "$new_dir" ]] || mkdir -p "$new_dir"

        if mv "$old_path" "$new_path"; then
            echo "  $(basename "$old_path") -> $(basename "$new_path")"
            # Write undo entry
            if [[ -n "$UNDO_FILE" ]]; then
                echo "mv $(printf '%q' "$new_path") $(printf '%q' "$old_path")" >> "$UNDO_FILE"
            fi
        else
            log_error "Failed: $old_path"
        fi
    fi
}

main() {
    parse_args "$@"

    if [[ ! -d "$TARGET_DIR" ]]; then
        log_error "Directory not found: $TARGET_DIR"
        exit 1
    fi

    # Validate mode requirements
    case "$MODE" in
        regex)
            if [[ -z "$PATTERN" ]]; then
                log_error "Regex mode requires pattern argument"
                exit 1
            fi
            ;;
        prefix|suffix)
            if [[ -z "$PATTERN" ]]; then
                log_error "$MODE mode requires a string argument"
                exit 1
            fi
            ;;
    esac

    [[ "$DRY_RUN" == true ]] && log_warn "DRY RUN MODE"

    if [[ -n "$UNDO_FILE" && "$DRY_RUN" == false ]]; then
        echo "#!/usr/bin/env bash" > "$UNDO_FILE"
        echo "# Undo script generated by bulk-rename.sh" >> "$UNDO_FILE"
        chmod +x "$UNDO_FILE"
    fi

    local count=0
    local num=$START_NUM

    log_info "Mode: $MODE | Directory: $TARGET_DIR"

    while IFS= read -r filepath; do
        local dir
        dir=$(dirname "$filepath")
        local filename
        filename=$(basename "$filepath")
        local name="${filename%.*}"
        local ext="${filename##*.}"
        [[ "$name" == "$ext" ]] && ext=""  # No extension

        local new_name=""

        case "$MODE" in
            regex)
                new_name=$(echo "$filename" | sed -E "s/$PATTERN/$REPLACEMENT/g")
                ;;
            prefix)
                new_name="${PATTERN}${filename}"
                ;;
            suffix)
                if [[ -n "$ext" ]]; then
                    new_name="${name}${PATTERN}.${ext}"
                else
                    new_name="${name}${PATTERN}"
                fi
                ;;
            sequential)
                local padded
                padded=$(printf "%04d" "$num")
                if [[ -n "$ext" ]]; then
                    new_name="${padded}.${ext}"
                else
                    new_name="${padded}"
                fi
                ((num++))
                ;;
            lowercase)
                new_name="${filename,,}"
                ;;
            uppercase)
                new_name="${filename^^}"
                ;;
            *)
                log_error "Unknown mode: $MODE"
                exit 1
                ;;
        esac

        rename_file "$filepath" "${dir}/${new_name}"
        ((count++))
    done < <(find_files "$TARGET_DIR")

    echo ""
    log_info "Processed $count file(s)"
    [[ -n "$UNDO_FILE" && "$DRY_RUN" == false ]] && log_info "Undo script: $UNDO_FILE"
}

main "$@"
